language: csharp
mono:
  - latest
  
solution: MineLib.PacketBuilder.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore MineLib.PacketBuilder.sln

script:
  - xbuild /p:Configuration=Release MineLib.PacketBuilder.sln
  - xbuild /p:Configuration=Debug MineLib.PacketBuilder.sln

notifications:
  email:
    on_success: always
